version: "3.8"

services:

  nodejs:
    container_name: node
    image: node:18-buster-slim
    ports:
      - 8000:8000
    working_dir: /app
    tty: true
    user: 1000:1000
    volumes:
      - ./:/app
    command: ["npm", "start"]
  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    container_name: adminer
    image: adminer:4
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_DB_DRIVER=postgresql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=mydb
    ports:
      - 8080:8080
    volumes:
      - ./deploy/adminer/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      - ./deploy/adminer/adminer.css:/tmp/adminer.css
    command: >
      sh -c "cp -f /tmp/adminer.css /var/www/html/adminer.css &&
            php -S [::]:8080 -t /var/www/html"

volumes:
  postgres_data: {}
